### ISSUE TITLE
StreamingKmeansExample例子中data/dir/training数据文件可否提供下？

### ISSUE THREAD

**Issue by ilevon** [jiangpz/LearnSpark#1]
JavaDStream<Vector> trainingData = jssc.textFileStream("data/dir/training").map(x -> Vectors.parse(x));
			JavaDStream<LabeledPoint> testData = jssc.textFileStream("data/dir/testing").map(x -> LabeledPoint.parse(x));

**Comment by jiangpz** [comment]
我提交了 这些数据是测试用的 测试spark streaming时通过StreamingKmeansTraining.java写入的
